version: '3.8'
services:
  db:
    container_name: pg_container_movies
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_movies
    ports:
      - "5432:5432"
volumes:
  pg_data:
